[build]
  command = "mkdir -p _site && echo 'Redirect' > _site/index.html"
  publish = "_site"
  ignore = "git diff --quiet HEAD^ HEAD"

[[redirects]]
  from = "/*"
  to = "https://samihadouaj.github.io/:splat"
  status = 301
  force = true
