# Service - Conference Reviews
# Add your reviewer experience here

- conference: "BIGDATA"
  role: "Reviewer" 
  year: "2022, 2023, 2024, 2025"
  # description: "Optional description of your review contribution."

- conference: "SIGMOD ARI"
  role: "Reproducibility Reviewer"
  year: "2024"

- conference: "ICDM"
  role: "Reviewer"
  year: "2025"
  # description: "Optional description of your role."

# Add more service experiences as needed
# - conference: "Another Conference"
#   role: "Reviewer"
#   year: "2023"
#   description: "Optional description"